---
repos:
  - repo: local
    hooks:
      - id: bump-version
        name: Bump version
        entry: python bump_version.py
        language: system
        pass_filenames: false # We won’t pass filenames here
        stages: [pre-commit] # Keep it as a pre-commit hook
