---
name: Publish Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine toml

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get latest commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Determine version bump type
        id: version_type
        run: |
          if echo "${{ env.message }}" | grep -iq "#major"; then
            echo "type=major" >> $GITHUB_ENV
          elif echo "${{ env.message }}" | grep -iq "#minor"; then
            echo "type=minor" >> $GITHUB_ENV
          else
            echo "type=patch" >> $GITHUB_ENV
          fi

      - name: Bump version
        run: |
          python bump_version.py ${{ env.type }}
          git add pyproject.toml
          git commit -m "Bump version: ${{ env.type }}"
          git tag $(grep -oP '(?<=version = ")\d+\.\d+\.\d+' pyproject.toml)

      - name: Push new version
        run: |
          git push origin main --tags

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
